repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.6.0
    hooks:
      - id: detect-secrets
