name: Semgrep Scan
on: [push, pull_request]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v2
        with:
          config: "p/ci"
